//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.08 at 04:17:36 PM IST 
//


package edu.iiitd.ivr.simulator.model.SUM;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the edu.iiitd.ivr.simulator.model.SUM package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: edu.iiitd.ivr.simulator.model.SUM
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SimpleUM }
     * 
     */
    public SimpleUM createCalls() {
        return new SimpleUM();
    }

    /**
     * Create an instance of {@link SimpleUM.Call }
     * 
     */
    public SimpleUM.Call createCallsCall() {
        return new SimpleUM.Call();
    }

    /**
     * Create an instance of {@link SimpleUM.Call.Events }
     * 
     */
    public SimpleUM.Call.Events createCallsCallEvents() {
        return new SimpleUM.Call.Events();
    }

    /**
     * Create an instance of {@link SimpleUM.Call.Metadata }
     * 
     */
    public SimpleUM.Call.Metadata createCallsCallMetadata() {
        return new SimpleUM.Call.Metadata();
    }

}
